In [1]:
import torch
import os

In [2]:
device="cuda" if torch.cuda.is_available else "cpu"
device

'cuda'

In [3]:
simple_tensor=torch.tensor([[1,3,5],[2,3,4]])
simple_tensor

tensor([[1, 3, 5],
        [2, 3, 4]])

In [4]:
type(simple_tensor)

torch.Tensor

In [5]:
simple_tensor.dtype

torch.int64

In [6]:
simple_tensor.size()

torch.Size([2, 3])

In [7]:
simple_tensor.shape

torch.Size([2, 3])

In [8]:
simple_tensor.requires_grad

False

In [11]:
simple_tensor.device

device(type='cpu')

In [12]:
tensor_2=torch.tensor([[2,4,5],[5,7,8],[90,4,56]],dtype=float,requires_grad=True,device=device)

In [13]:
tensor_2.device

device(type='cuda', index=0)

In [14]:
tensor_2.dtype

torch.float64

## commonly used tensors 

In [23]:
zero_tensor=torch.empty(size=(3,3))  
zero_tensor

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [24]:
one_tensor=torch.ones(size=(3,3))
one_tensor

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [26]:
random_tensor=torch.rand(size=[3,4])
random_tensor

tensor([[0.2859, 0.3927, 0.6309, 0.9655],
        [0.9283, 0.6906, 0.3549, 0.0126],
        [0.1869, 0.4460, 0.2277, 0.0011]])

In [30]:
identity_tensor=torch.eye(3)
identity_tensor

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [34]:
arange_tensor=torch.arange(start=1,end=20,step=2)
arange_tensor

tensor([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [39]:
linspace_tensor=torch.linspace(start=1,end=2,steps=20)
linspace_tensor

tensor([1.0000, 1.0526, 1.1053, 1.1579, 1.2105, 1.2632, 1.3158, 1.3684, 1.4211,
        1.4737, 1.5263, 1.5789, 1.6316, 1.6842, 1.7368, 1.7895, 1.8421, 1.8947,
        1.9474, 2.0000])

In [42]:
normal_dist_tensor=torch.linspace(start=1,end=3,steps=10).normal_(mean=0,std=1)
normal_dist_tensor

tensor([ 1.3910,  0.6300,  1.8404,  0.6303, -0.1216,  0.1533,  0.1740,  2.2909,
         1.0918, -0.1215])

In [46]:
diag_tensor=torch.diag(5*torch.ones(4))
diag_tensor

tensor([[5., 0., 0., 0.],
        [0., 5., 0., 0.],
        [0., 0., 5., 0.],
        [0., 0., 0., 5.]])

## conversion of tensors

In [47]:
num_tensor=torch.arange(5)
num_tensor

tensor([0, 1, 2, 3, 4])

In [52]:
new_tensor=num_tensor.bool()  ## converting to bool type tensor
new_tensor

tensor([False,  True,  True,  True,  True])

In [53]:
new_tensor.dtype

torch.bool

In [54]:
num_tensor.short()

tensor([0, 1, 2, 3, 4], dtype=torch.int16)

In [55]:
num_tensor.long()

tensor([0, 1, 2, 3, 4])

In [56]:
num_tensor.half()

tensor([0., 1., 2., 3., 4.], dtype=torch.float16)

In [57]:
num_tensor.float()

tensor([0., 1., 2., 3., 4.])

In [58]:
num_tensor.double()

tensor([0., 1., 2., 3., 4.], dtype=torch.float64)

### converting tensor to numpy array 

In [60]:
import numpy as np

In [61]:
num_array=np.array([[1,2,3],[4,5,6]])

In [63]:
torch.from_numpy(num_array)

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)

In [64]:
torch.tensor(num_array)

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)

In [66]:
tensor_arr=torch.tensor([[1,2,3],[4,5,6]])
numpy_array=tensor_arr.numpy() # coverts into numpy array

In [67]:
numpy_array

array([[1, 2, 3],
       [4, 5, 6]], dtype=int64)

In [68]:
type(numpy_array)

numpy.ndarray