In [1]:
import torch
import numpy
import os

In [2]:
x=torch.arange(start=10,end=20,step=3)
y=torch.arange(start=25,end=35,step=3)

x.shape,y.shape

(torch.Size([4]), torch.Size([4]))

    Addition element wise

In [3]:
print(x,y)

tensor([10, 13, 16, 19]) tensor([25, 28, 31, 34])


In [4]:
x+y

tensor([35, 41, 47, 53])

Multiplication element wise

In [5]:
x*y

tensor([250, 364, 496, 646])

Division element wise

In [6]:
x/y

tensor([0.4000, 0.4643, 0.5161, 0.5588])

In [7]:
z=torch.ones(4)
z,x

(tensor([1., 1., 1., 1.]), tensor([10, 13, 16, 19]))

In [8]:
x+z

tensor([11., 14., 17., 20.])

In place addition 

In [9]:
z.add_(x)  # updates z value

tensor([11., 14., 17., 20.])

In [10]:
z

tensor([11., 14., 17., 20.])

In [11]:
x.pow(2)  ## power of x tensor

tensor([100, 169, 256, 361])

comparision of tensor values

x>0  # compares each value 

Matrix multiplication 

In [12]:
a=torch.rand(size=(3,5))
b=torch.rand(size=(5,3))

a @ b  ## matrix multiplication 

tensor([[2.4302, 1.3418, 1.2775],
        [1.8522, 1.3997, 0.8029],
        [2.3354, 1.4943, 0.8333]])

In [13]:
a.matmul(b)  ## matrix multilication

tensor([[2.4302, 1.3418, 1.2775],
        [1.8522, 1.3997, 0.8029],
        [2.3354, 1.4943, 0.8333]])

In [14]:
t=torch.rand(3,3)
print(t)
t.matrix_exp()  ## exponentiation of square matrix

tensor([[0.3553, 0.5539, 0.4511],
        [0.7559, 0.0146, 0.4520],
        [0.9696, 0.4254, 0.7165]])


tensor([[2.2063, 0.9710, 1.1178],
        [1.4655, 1.5078, 1.0692],
        [2.2300, 1.1782, 2.7613]])

In [15]:
r=torch.tensor([[2,2],[3,4]])
r

tensor([[2, 2],
        [3, 4]])

In [16]:
r.matrix_power(2)

tensor([[10, 12],
        [18, 22]])

dot product 

In [17]:
s=torch.tensor([2,3,4])
t=torch.tensor([6,7,9])

In [18]:
s.dot(t)

tensor(69)

In [19]:
sum(s*t) ## dot product

tensor(69)

## Broadcasting 

In [20]:
s

tensor([2, 3, 4])

In [21]:
s+1  # adding 1 to each element of tensor s. this is broadcasting 

tensor([3, 4, 5])

In [22]:
s*5   # multiplying 5 to each element of tensor s. this is broadcasting 

tensor([10, 15, 20])

In [23]:
tensor1=torch.tensor([[2,3,4],[5,6,7]])
tensor1

tensor([[2, 3, 4],
        [5, 6, 7]])

In [24]:
ones=torch.ones(size=(1,3))
ones

tensor([[1., 1., 1.]])

In [25]:
tensor1-ones  ## broadcasting -> subtracting 1 from each element from tensor1

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [26]:
tensor1+ones ## broadcasting -> adding 1 from each element from tensor1

tensor([[3., 4., 5.],
        [6., 7., 8.]])

Broadcasting across columns also works similarly as row wise operation above.

In [27]:
tensor1.sum()  ## sum of the elements of tensor elements

tensor(27)

In [28]:
A = torch.rand(size=(3,4))
A

tensor([[0.5590, 0.2700, 0.2700, 0.4121],
        [0.6980, 0.1928, 0.7009, 0.5032],
        [0.8144, 0.9457, 0.7466, 0.8259]])

In [29]:
A.max()

tensor(0.9457)

In [30]:
A.argmax()

tensor(9)

In [31]:
A.min()

tensor(0.1928)

In [32]:
A.argmin()

tensor(5)

In [33]:
torch.max(A),torch.argmax(A)

(tensor(0.9457), tensor(9))

In [34]:
torch.min(A),torch.argmin(A)

(tensor(0.1928), tensor(5))

In [35]:
torch.max(A,dim=1)

torch.return_types.max(
values=tensor([0.5590, 0.7009, 0.9457]),
indices=tensor([0, 2, 1]))

In [36]:
torch.min(A,dim=1)

torch.return_types.min(
values=tensor([0.2700, 0.1928, 0.7466]),
indices=tensor([1, 1, 2]))

In [37]:
torch.min(A,dim=0)

torch.return_types.min(
values=tensor([0.5590, 0.1928, 0.2700, 0.4121]),
indices=tensor([0, 1, 0, 0]))

In [38]:
torch.max(A,dim=0)

torch.return_types.max(
values=tensor([0.8144, 0.9457, 0.7466, 0.8259]),
indices=tensor([2, 2, 2, 2]))

In [39]:
torch.abs(-A)

tensor([[0.5590, 0.2700, 0.2700, 0.4121],
        [0.6980, 0.1928, 0.7009, 0.5032],
        [0.8144, 0.9457, 0.7466, 0.8259]])

In [41]:
torch.argmax(A,dim=1)

tensor([0, 2, 1])

In [42]:
torch.mean(A)

tensor(0.5782)

In [43]:
A

tensor([[0.5590, 0.2700, 0.2700, 0.4121],
        [0.6980, 0.1928, 0.7009, 0.5032],
        [0.8144, 0.9457, 0.7466, 0.8259]])

In [45]:
B=torch.ones(size=A.shape)

In [46]:
A>B

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [47]:
A==B

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [49]:
A.eq(B)

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [50]:
A<B

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [52]:
torch.sort(A)

torch.return_types.sort(
values=tensor([[0.2700, 0.2700, 0.4121, 0.5590],
        [0.1928, 0.5032, 0.6980, 0.7009],
        [0.7466, 0.8144, 0.8259, 0.9457]]),
indices=tensor([[1, 2, 3, 0],
        [1, 3, 0, 2],
        [2, 0, 3, 1]]))