In [1]:
import torch
import numpy as np

# Indexing ,Slicing

In [2]:
x=torch.rand(size=[3,4])
x

tensor([[0.6553, 0.9127, 0.0074, 0.0239],
        [0.4374, 0.7728, 0.1631, 0.2685],
        [0.2803, 0.6956, 0.2381, 0.0267]])

In [3]:
x[0,1],x[0][1]

(tensor(0.9127), tensor(0.9127))

In [4]:
x[0,:]

tensor([0.6553, 0.9127, 0.0074, 0.0239])

In [5]:
x[1,:]

tensor([0.4374, 0.7728, 0.1631, 0.2685])

In [6]:
x[0:2,0:3]

tensor([[0.6553, 0.9127, 0.0074],
        [0.4374, 0.7728, 0.1631]])

In [7]:
x[0:2,0:3:2]  ## with steps

tensor([[0.6553, 0.0074],
        [0.4374, 0.1631]])

In [10]:
x[0,1]=989

In [11]:
x[0,1]

tensor(989.)

In [12]:
x

tensor([[6.5535e-01, 9.8900e+02, 7.4241e-03, 2.3857e-02],
        [4.3736e-01, 7.7276e-01, 1.6314e-01, 2.6846e-01],
        [2.8035e-01, 6.9557e-01, 2.3810e-01, 2.6730e-02]])

In [13]:
y=torch.rand(size=[3,4])

In [14]:
y

tensor([[0.9826, 0.1245, 0.2556, 0.8415],
        [0.7845, 0.6435, 0.8286, 0.8220],
        [0.0497, 0.7158, 0.7226, 0.0651]])

## concat

In [15]:
torch.concat((x,y),dim=1)

tensor([[6.5535e-01, 9.8900e+02, 7.4241e-03, 2.3857e-02, 9.8261e-01, 1.2454e-01,
         2.5560e-01, 8.4151e-01],
        [4.3736e-01, 7.7276e-01, 1.6314e-01, 2.6846e-01, 7.8455e-01, 6.4354e-01,
         8.2863e-01, 8.2200e-01],
        [2.8035e-01, 6.9557e-01, 2.3810e-01, 2.6730e-02, 4.9694e-02, 7.1580e-01,
         7.2256e-01, 6.5098e-02]])

In [16]:
torch.concat((x,y),dim=0)

tensor([[6.5535e-01, 9.8900e+02, 7.4241e-03, 2.3857e-02],
        [4.3736e-01, 7.7276e-01, 1.6314e-01, 2.6846e-01],
        [2.8035e-01, 6.9557e-01, 2.3810e-01, 2.6730e-02],
        [9.8261e-01, 1.2454e-01, 2.5560e-01, 8.4151e-01],
        [7.8455e-01, 6.4354e-01, 8.2863e-01, 8.2200e-01],
        [4.9694e-02, 7.1580e-01, 7.2256e-01, 6.5098e-02]])

In [17]:
x.reshape(2,6)

tensor([[6.5535e-01, 9.8900e+02, 7.4241e-03, 2.3857e-02, 4.3736e-01, 7.7276e-01],
        [1.6314e-01, 2.6846e-01, 2.8035e-01, 6.9557e-01, 2.3810e-01, 2.6730e-02]])

In [18]:
y.reshape(4,3)

tensor([[0.9826, 0.1245, 0.2556],
        [0.8415, 0.7845, 0.6435],
        [0.8286, 0.8220, 0.0497],
        [0.7158, 0.7226, 0.0651]])

In [19]:
y.reshape(1,12)

tensor([[0.9826, 0.1245, 0.2556, 0.8415, 0.7845, 0.6435, 0.8286, 0.8220, 0.0497,
         0.7158, 0.7226, 0.0651]])

In [20]:
x.reshape(12,1)

tensor([[6.5535e-01],
        [9.8900e+02],
        [7.4241e-03],
        [2.3857e-02],
        [4.3736e-01],
        [7.7276e-01],
        [1.6314e-01],
        [2.6846e-01],
        [2.8035e-01],
        [6.9557e-01],
        [2.3810e-01],
        [2.6730e-02]])

In [21]:
x.flatten() 

tensor([6.5535e-01, 9.8900e+02, 7.4241e-03, 2.3857e-02, 4.3736e-01, 7.7276e-01,
        1.6314e-01, 2.6846e-01, 2.8035e-01, 6.9557e-01, 2.3810e-01, 2.6730e-02])

In [23]:
x.view(-1)  ## flattening operation 1 row 

tensor([6.5535e-01, 9.8900e+02, 7.4241e-03, 2.3857e-02, 4.3736e-01, 7.7276e-01,
        1.6314e-01, 2.6846e-01, 2.8035e-01, 6.9557e-01, 2.3810e-01, 2.6730e-02])

In [25]:
batch=16
## batch flattening 
torch.rand((batch,2,5)).view(batch,-1)

tensor([[0.3195, 0.2079, 0.2806, 0.5084, 0.7316, 0.7859, 0.5871, 0.5559, 0.9434,
         0.5880],
        [0.1925, 0.8026, 0.3687, 0.5465, 0.7293, 0.8026, 0.6336, 0.3399, 0.6268,
         0.7775],
        [0.0499, 0.5473, 0.6360, 0.5286, 0.2073, 0.2855, 0.6495, 0.5837, 0.1854,
         0.5043],
        [0.7538, 0.8846, 0.3360, 0.0473, 0.5851, 0.8978, 0.6138, 0.1590, 0.6474,
         0.2168],
        [0.1490, 0.5625, 0.4278, 0.9106, 0.9828, 0.6204, 0.3697, 0.7228, 0.6664,
         0.2760],
        [0.9259, 0.5988, 0.3761, 0.7951, 0.4083, 0.0273, 0.7763, 0.5821, 0.2733,
         0.4083],
        [0.3754, 0.1781, 0.7197, 0.7949, 0.8683, 0.4279, 0.7586, 0.4966, 0.5045,
         0.2971],
        [0.1400, 0.3654, 0.5070, 0.3643, 0.8964, 0.1121, 0.7009, 0.3885, 0.1426,
         0.2155],
        [0.1210, 0.6900, 0.8270, 0.5417, 0.4682, 0.8971, 0.9453, 0.7563, 0.5702,
         0.7498],
        [0.0196, 0.8288, 0.4791, 0.4938, 0.6446, 0.9298, 0.1590, 0.7235, 0.3050,
         0.7888],
        [0